ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.aliases ~/.aliases
ln -s ~/dotfiles/.profile ~/.profile
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.profile ~/.profile
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.latexmkrc ~/.latexmkrc
ln -s ~/dotfiles/.geeknoterc ~/.geeknoterc
ln -s ~/dotfiles/userautoload ~/.vim/userautoload
ln -s ~/dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim
ln -s ~/dotfiles/.config/nvim/dein.toml ~/.config/nvim/dein.toml
