[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
" unite
let g:unite_enable_start_insert=1
if executable('ag')
	let g:unite_source_grep_command = 'ag'
	let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
	let g:unite_source_grep_recursive_opt = ''
endif
" unite outline
noremap <Leader>o :Unite -vertical -winwidth=30 outline <CR> <esc>
noremap <Leader>ff :Unite file_mru<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
				let g:lightline = { 
				\   'colorscheme': 'wombat'
				\}
'''

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
hook_add = '''
				set t_Co=256
				set background=light
				colorscheme PaperColor
'''

[[plugins]]
repo = 'lervag/vim-latex'
hook_add = '''
if !exists('g:deoplete#omni_patterns')
    let g:deoplete#omni_patterns = {}
endif
let g:deoplete#omni_patterns.tex =
            \ '\v\\%('
            \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
            \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
            \ . '|hyperref\s*\[[^]]*'
            \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
            \ . '|%(include%(only)?|input)\s*\{[^}]*'
            \ . ')\m'
'''

[[plugins]]
repo = 'matze/vim-tex-fold'

[[plugins]]
repo = 'zchee/deoplete-jedi'


[[plugins]]
repo = 'ujihisa/neco-look'
